# controller/controller-deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: sd-controller
  namespace: stable-diffusion-multiplayer
  labels:
    app: sd-controller
spec:
  replicas: 1
  selector:
    matchLabels:
      app: sd-controller
  template:
    metadata:
      labels:
        app: sd-controller
    spec:
      serviceAccountName: sd-controller
      containers:
      - name: controller
        image: primay73/sd-controller:test
        imagePullPolicy: Always
        env:
        - name: NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        resources:
          requests:
            memory: "256Mi"
            cpu: "100m"
          limits:
            memory: "512Mi"
            cpu: "500m"
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: sd-controller
  namespace: stable-diffusion-multiplayer
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: sd-controller
rules:
- apiGroups: [""]
  resources: ["pods", "services", "configmaps", "secrets", "persistentvolumeclaims"]
  verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]
- apiGroups: ["apps"]
  resources: ["deployments"]
  verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]
- apiGroups: ["networking.k8s.io"]
  resources: ["ingresses"]
  verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]
- apiGroups: ["ai.example.com"]
  resources: ["sdmultiplayers", "sdmultiplayers/status"]
  verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: sd-controller
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: sd-controller
subjects:
- kind: ServiceAccount
  name: sd-controller
  namespace: stable-diffusion-multiplayer