version: '3.8'

services:
  # 后端服务
  backend:
    build:
      context: .
      dockerfile: docker/backend.Dockerfile
    container_name: sd-multiplayer-backend
    environment:
      - STABILITY_API_KEY=${STABILITY_API_KEY}
      - LIVEBLOCKS_SECRET=${LIVEBLOCKS_SECRET}
    volumes:
      - ./data/storage:/app/stablediffusion-infinity/local_storage
      - ./data/db:/app/stablediffusion-infinity/rooms.db
    ports:
      - "7860:7860"
    # 移除 GPU 资源配置，API 代理服务无需 GPU
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:7860/server/api/rooms"]
      interval: 30s
      timeout: 10s
      retries: 3

  # 前端服务
  frontend:
    build:
      context: .
      dockerfile: docker/frontend.Dockerfile
    container_name: sd-multiplayer-frontend
    ports:
      - "80:80"
    depends_on:
      - backend
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost/health"]
      interval: 30s
      timeout: 10s
      retries: 3

volumes:
  storage_data:
  db_data: 