apiVersion: v1
kind: ConfigMap
metadata:
  name: sd-multiplayer-config
  namespace: stable-diffusion-multiplayer
  labels:
    app: sd-multiplayer
data:
  # 应用配置
  APP_ENV: "production"
  LOG_LEVEL: "info"
  
  # 后端配置
  BACKEND_HOST: "0.0.0.0"
  BACKEND_PORT: "7860"
  
  # 数据库配置
  DATABASE_PATH: "/app/data/rooms.db"
  STORAGE_PATH: "/app/data/storage"
  
  # Nginx 配置
  NGINX_WORKER_PROCESSES: "auto"
  NGINX_WORKER_CONNECTIONS: "1024" 