apiVersion: v1
kind: Secret
metadata:
  name: sd-multiplayer-secrets
  namespace: stable-diffusion-multiplayer
  labels:
    app: sd-multiplayer
type: Opaque
data:
  # 注意：这些值需要是 base64 编码的
  # 使用命令：echo -n "你的密钥" | base64
  
  # Stability AI API 密钥
  # stability-api-key: <base64-encoded-api-key>
  
  # Liveblocks Secret
  # liveblocks-secret: <base64-encoded-secret>
  
  # 示例（请替换为实际的 base64 编码值）:
  stability-api-key: ""  # 替换为: echo -n "sk-your-stability-api-key" | base64
  liveblocks-secret: ""  # 替换为: echo -n "sk_your_liveblocks_secret" | base64

---
# 用于创建 Secret 的脚本（不会被应用到集群）
# 创建方法：
# kubectl create secret generic sd-multiplayer-secrets \
#   --from-literal=stability-api-key="your-stability-api-key" \
#   --from-literal=liveblocks-secret="your-liveblocks-secret" \
#   --namespace=stable-diffusion-multiplayer 