# 存储类定义
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: sd-multiplayer-storage
provisioner: kubernetes.io/no-provisioner
volumeBindingMode: WaitForFirstConsumer
allowVolumeExpansion: true

---
# 数据库持久化存储
apiVersion: v1
kind: PersistentVolume
metadata:
  name: sd-multiplayer-db-pv
  labels:
    app: sd-multiplayer
    type: database
spec:
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: sd-multiplayer-storage
  hostPath:
    path: /tmp/sd-multiplayer/database
    type: DirectoryOrCreate

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: sd-multiplayer-db-pvc
  namespace: stable-diffusion-multiplayer
  labels:
    app: sd-multiplayer
    type: database
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
  storageClassName: sd-multiplayer-storage

---
# 文件存储持久化存储
apiVersion: v1
kind: PersistentVolume
metadata:
  name: sd-multiplayer-storage-pv
  labels:
    app: sd-multiplayer
    type: files
spec:
  capacity:
    storage: 100Gi
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  storageClassName: sd-multiplayer-storage
  hostPath:
    path: /tmp/sd-multiplayer/storage
    type: DirectoryOrCreate

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: sd-multiplayer-storage-pvc
  namespace: stable-diffusion-multiplayer
  labels:
    app: sd-multiplayer
    type: files
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 100Gi
  storageClassName: sd-multiplayer-storage

