PRAGMA foreign_keys=OFF;
BEGIN TRANSACTION;
CREATE TABLE rooms (id INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL, room_id TEXT NOT NULL, users_count INTEGER NOT NULL DEFAULT 0);
INSERT INTO rooms VALUES(1,'sd-multiplayer-room-0',0);
INSERT INTO rooms VALUES(2,'sd-multiplayer-room-1',0);
INSERT INTO rooms VALUES(3,'sd-multiplayer-room-2',0);
INSERT INTO rooms VALUES(4,'sd-multiplayer-room-3',0);
INSERT INTO rooms VALUES(5,'sd-multiplayer-room-4',0);
INSERT INTO rooms VALUES(6,'sd-multiplayer-room-5',0);
INSERT INTO rooms VALUES(7,'sd-multiplayer-room-6',0);
INSERT INTO rooms VALUES(8,'sd-multiplayer-room-7',0);
INSERT INTO rooms VALUES(9,'sd-multiplayer-room-8',0);
INSERT INTO rooms VALUES(10,'sd-multiplayer-room-9',0);
INSERT INTO rooms VALUES(11,'sd-multiplayer-room-10',0);
INSERT INTO rooms VALUES(12,'sd-multiplayer-room-11',0);
INSERT INTO rooms VALUES(13,'sd-multiplayer-room-12',0);
INSERT INTO rooms VALUES(14,'sd-multiplayer-room-13',0);
INSERT INTO rooms VALUES(15,'sd-multiplayer-room-14',0);
INSERT INTO rooms VALUES(16,'sd-multiplayer-room-15',0);
INSERT INTO rooms VALUES(17,'sd-multiplayer-room-16',0);
INSERT INTO rooms VALUES(18,'sd-multiplayer-room-17',0);
INSERT INTO rooms VALUES(19,'sd-multiplayer-room-18',0);
INSERT INTO rooms VALUES(20,'sd-multiplayer-room-19',0);
DELETE FROM sqlite_sequence;
INSERT INTO sqlite_sequence VALUES('rooms',20);
COMMIT;
